[package]
name = "gejang"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.11", features = ["derive"] }
colored = "2.1.0"
itertools = "0.13.0"
strum = "0.26.3"
strum_macros = "0.26.4"
thiserror = "1.0.63"

[dev-dependencies]
rstest = "0.22.0"
